name: "net-basic"
version: "1.0"

channels:
  mychannel:
    orderers:
      - orderer.hyperfabric.xyz

    peers:
      peer0.org1.hyperfabric.xyz:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.hyperfabric.xyz:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.hyperfabric.xyz
    certificateAuthorities:
      - ca.org1.hyperfabric.xyz
    adminPrivateKey:
      path: artifacts/crypto-config/peerOrganizations/org1.hyperfabric.xyz/users/Admin@org1.hyperfabric.xyz/msp/keystore/dfda1333c2e184a697aa3ca4192473ff39e14472534afe44a7a5b5ab26a887ad_sk
    signedCert:
      path: artifacts/crypto-config/peerOrganizations/org1.hyperfabric.xyz/users/Admin@org1.hyperfabric.xyz/msp/signcerts/Admin@org1.hyperfabric.xyz-cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.hyperfabric.xyz
      - peer1.org2.hyperfabric.xyz
    certificateAuthorities:
      - ca.org2.hyperfabric.xyz
    adminPrivateKey:
      path: artifacts/crypto-config/peerOrganizations/org2.hyperfabric.xyz/users/Admin@org2.hyperfabric.xyz/msp/keystore/e320fa22b617574f85fcd611f767fdc0b741533b611585b0e47303bb75390b1c_sk
    signedCert:
      path: artifacts/crypto-config/peerOrganizations/org2.hyperfabric.xyz/users/Admin@org2.hyperfabric.xyz/msp/signcerts/Admin@org2.hyperfabric.xyz-cert.pem

orderers:
  orderer.hyperfabric.xyz:
    url: grpcs://orderer.hyperfabric.xyz:7050
    grpcOptions:
      ssl-target-name-override: orderer.hyperfabric.xyz
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: artifacts/crypto-config/ordererOrganizations/hyperfabric.xyz/orderers/orderer.hyperfabric.xyz/tls/ca.crt

peers:
  peer0.org1.hyperfabric.xyz:
    url: grpcs://peer0.org1.hyperfabric.xyz:7051
    eventUrl: grpcs://peer0.org1.hyperfabric.xyz:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.hyperfabric.xyz
    tlsCACerts:
      path: artifacts/crypto-config/peerOrganizations/org1.hyperfabric.xyz/peers/peer0.org1.hyperfabric.xyz/tls/ca.crt

  peer0.org2.hyperfabric.xyz:
    url: grpcs://peer0.org2.hyperfabric.xyz:7051
    eventUrl: grpcs://peer0.org2.hyperfabric.xyz:7053
    grpcOptions:
      ssl-target-name-override: peer0.org2.hyperfabric.xyz
    tlsCACerts:
      path: artifacts/crypto-config/peerOrganizations/org2.hyperfabric.xyz/peers/peer0.org2.hyperfabric.xyz/tls/ca.crt

certificateAuthorities:
  ca.org1.hyperfabric.xyz:
    url: https://ca.org1.hyperfabric.xyz:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/crypto-config/peerOrganizations/org1.hyperfabric.xyz/ca/ca.org1.hyperfabric.xyz-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.org1.hyperfabric.xyz

  ca.org2.hyperfabric.xyz:
    url: https://ca.org2.hyperfabric.xyz:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/crypto-config/peerOrganizations/org2.hyperfabric.xyz/ca/ca.org2.hyperfabric.xyz-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.org2.hyperfabric.xyz